// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoqfgfBtXFzk1SR-PpZBSuI6JGmvOTMxg',
    appId: '1:473154866578:web:51eb3dd4610128f2dbc54b',
    messagingSenderId: '473154866578',
    projectId: 't-action-39912',
    authDomain: 't-action-39912.firebaseapp.com',
    storageBucket: 't-action-39912.appspot.com',
    measurementId: 'G-LVDJXLNBX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWrqYyYFTSLNJO9_HQ35YKjGuUor4WdSg',
    appId: '1:473154866578:android:5707eb8efd81b1a8dbc54b',
    messagingSenderId: '473154866578',
    projectId: 't-action-39912',
    storageBucket: 't-action-39912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMXKUetkUHOKr37P8K9qe3OrXsdREyC_o',
    appId: '1:473154866578:ios:0bfe50caee667d97dbc54b',
    messagingSenderId: '473154866578',
    projectId: 't-action-39912',
    storageBucket: 't-action-39912.appspot.com',
    iosBundleId: 'com.example.tAction',
  );
}
